language: node_js
node_js:
  - "8.4.0"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

#Deployment
after_success: >
  if ([ ! -z "$DEPLOY_TOKEN" ] && [ "$TRAVIS_BRANCH" == master ] && [ -z "$TRAVIS_TAG" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]); then
    echo "Deploying";
    git config --global user.email "login+travis@elo7.com";
    git config --global user.name "Travis ci";
    git remote rm origin;
    git remote add origin "https://$DEPLOY_USER:$DEPLOY_TOKEN@github.com/$TRAVIS_REPO_SLUG.git";
    npm run deploy;
    echo "Deployed";
  else
    echo "Skipped deploy"
  fi
